core/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views


app_name = 'core'
urlpatterns = [
    # ''
    path('', views.index, name='index'),
    path('adicionar-paciente', views.adicionaPaciente, name="adicionaPaciente"),
    path('pacientes', views.pacientes, name='pacientes'),
    path('paciente/<paciente_id>', views.editPaciente, name='editaPaciente'),
    path('agendamento', views.novoAgendamento, name='novoAgendamento'),
    path('editar-agendamento/<agenda_id>', views.editaAgendamento, name="editarAgendamento"),
    path('historico/<paciente_id>', views.historicoPaciente, name='historicoPaciente'),
    path('login/', login, {'template_name': 'core/login.html'}, name='login'),
    path('logout', views.logout_user, name='logout_page')

]

estetica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core')
]

core/models.py
from django.db import models
from django.contrib import admin
from django.utils.timezone import now
import datetime
# Create your models here.


class FormPagamento(models.Model):
    """Modelo que irá criar as formas de pagamento"""
    forma = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Formas de Pagamento"

    def __str__(self):
        return self.forma


class StatusConsulta(models.Model):
    """Modelo que irá criar os status da consulta Realizada/Cancelada/Remarcada"""
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.status


class Servico(models.Model):
    """Modelo que irá cadastrar os tipos de serviços oferecidos pela clinica"""
    servico = models.CharField(max_length=200)
    valor = models.DecimalField(max_digits=8, decimal_places=2)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.servico


class ServicoAdmin(admin.ModelAdmin):
    """ Classe que define a forma que os serviços serão apresentados no site de administração """
    list_display = ('servico', 'valor', 'data_criacao')


class Paciente(models.Model):
    """Modelo que irá Criar os Pacientes da Clinica"""

    nome = models.CharField(max_length=250)
    nascimento = models.DateField(null=True, blank=True)
    cpf = models.CharField(max_length=15, null=True, blank=True)
    profissao = models.CharField(max_length=250, null=True, blank=True)
    celular = models.CharField(max_length=20)
    email = models.CharField(max_length=100, null=True, blank=True)
    cep = models.CharField(max_length=15, null=True, blank=True)
    endereco = models.CharField(max_length=250, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome


class PacienteAdmin(admin.ModelAdmin):
    """Classe que define como o modelo será mostrado no site de administração do django"""
    list_display = ('nome', 'email', 'cpf', 'data_criacao')


class Agenda(models.Model):
    """Criação da agenda de consultas da Clinica"""
    data_consulta = models.DateField()
    hora_inicio = models.TimeField()
    hora_final = models.TimeField()
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    servico = models.ForeignKey(Servico, on_delete=models.DO_NOTHING)
    observacoes = models.TextField()
    status = models.ForeignKey(StatusConsulta, null=True, blank=True, on_delete=models.DO_NOTHING, default=1)
    form_pagamento = models.ForeignKey(FormPagamento, null=True, blank=True, on_delete=models.DO_NOTHING)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.servico.servico

    class Meta:
        verbose_name = "Agenda"


class AgendaAdmin(admin.ModelAdmin):
    """Classe que define como as informações das consultas serão mostradas no painel ADM"""
    list_display = ('data_consulta', 'paciente', 'servico', 'status')

core/forms.py
from django import forms
from .models import Paciente, Agenda


class DateInput(forms.DateInput):
    input_type = 'datetime-local'


class PacienteForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['nome', 'nascimento', 'cpf', 'profissao', 'celular', 'email', 'cep', 'endereco', 'cidade']

class AgendaForm(forms.ModelForm):
    class Meta:
        model = Agenda
        fields = ['paciente', 'servico', 'data_consulta', 'hora_inicio', 'hora_final', 'observacoes', 'status', 'form_pagamento']
        labels = {'paciente': 'Paciente', 'servico': 'Serviço', 'data_consulta': 'Data da Consulta',
                  'hora_inicio': 'Horario de Início', 'hora_final': 'Horario Final',
                  'observacoes': 'Observações', 'status': 'Status', 'form_pagamento': 'Forma de Pagamento'}

core/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from . import models
from .forms import PacienteForm, AgendaForm
import datetime
# Create your views here.


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:index'))


@login_required
def index(request):
    """Página inicial"""
    agenda = models.Agenda.objects.all()
    for var in agenda:
        a = var.observacoes.replace("\n", "").replace('\r', '')
        var.observacoes = a

    context = {'agenda': agenda}
    return render(request, 'core/index.html', context)


@login_required
def adicionaPaciente(request):
    """Adiciona um novo paciente"""
    if request.method != 'POST':
        # Nenhum dado submetido, cria o formulário em branco
        form = PacienteForm
    else:
        # Caso o formulário venha preenchido os dados precisam ser salvos no banco
        form = PacienteForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:pacientes'))
    context = {'form': form}
    return render(request, 'core/adicionaPaciente.html', context)

@login_required
def pacientes(request):
    """Mostra lista de pacientes do consultorio"""
    pacientes = models.Paciente.objects.all()
    context = {'pacientes': pacientes}
    return render(request, 'core/pacientes.html', context)

@login_required
def editPaciente(request, paciente_id):
    """Recebe um paciente para edição"""
    paciente = models.Paciente.objects.get(id=paciente_id)
    if request.method != 'POST':
        form = PacienteForm(instance=paciente)
    else:
        # Processa dados para edição de paciente
        form = PacienteForm(instance=paciente, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:pacientes'))
    context = {'form': form, 'paciente': paciente}
    return render(request, 'core/editaPaciente.html', context)

@login_required
def novoAgendamento(request):
    """Cadastra novos agendamentos"""
    if request.method != 'POST':
        form = AgendaForm
    else:
        form = AgendaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:index'))
    context = {'form': form}
    return render(request, 'core/cadastraConsulta.html', context)

@login_required
def editaAgendamento(request, agenda_id):
    """Edita um agendamento de consulta"""
    agenda = models.Agenda.objects.get(id=agenda_id)
    if request.method != 'POST':
        form = AgendaForm(instance=agenda)
    else:
        form = AgendaForm(instance=agenda, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:index'))
    context = {'form': form, 'agenda': agenda}
    return render(request, 'core/editaConsulta.html', context)

@login_required
def historicoPaciente(request, paciente_id):
    """Retorna um histórico do paciente selecionado"""
    paciente = models.Paciente.objects.get(id=paciente_id)
    historico = models.Agenda.objects.filter(paciente=paciente_id, data_consulta__lte=datetime.datetime.now())
    # Verifica se o pacientee realizou algum consulta e não pagou, ou pagou e a consulta não foi realizada.
    saldo = 0;
    for hist in historico:
        if hist.status.id == 2 and hist.form_pagamento is None:
           saldo += hist.servico.valor
        elif hist.status.id == 1 and hist.form_pagamento is not None:
            saldo -= hist.servico.valor
    context = {'historico': historico, 'paciente': paciente, 'saldo': saldo}
    return render(request, 'core/historico.html', context)

core/templates/core/adicionaPaciente.html
{% extends 'core/base.html'%}
{% load widget_tweaks %}
{% block content %}
<div class="page-header text-center mb-3">
    <h1 class="text-secondary">Adiciona Paciente</h1>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="{% url 'core:adicionaPaciente' %}" method="post">
            {% csrf_token %}
             <div class="form-group">
                 <label for="{{ form.nome.id_for_label }}">Nome</label>
                 {{ form.nome | add_class:"form-control"}}

                <label>Nascimento</label>
                {{ form.nascimento | add_class:"form-control data"}}
            
           
                <label for="{{ form.cpf.id_for_label }}">RG</label>
                {{ form.cpf | add_class:"form-control" }}

                 <label for="{{ form.cpf.id_for_label }}">Profissão</label>
                {{ form.profissao | add_class:"form-control" }}
           
            
                <label for="{{ form.celular.id_for_label }}">Celular</label>
                {{ form.celular | add_class:"form-control celular" }}
           
            
                <label for="{{ form.email.id_for_label }}">Email</label>
                {{ form.email | add_class:"form-control" }}
           
            
                <label for="{{ form.cep.id_for_label }}">CEP</label>
                {{ form.cep | add_class:"form-control cep" }}
           
            
                <label for="{{ form.endereco.id_for_label }}">Endereço</label>
                {{ form.endereco | add_class:"form-control" }}
           
           
                <label for="{{ form.cidade.id_for_label }}">Cidade</label>
                {{ form.cidade | add_class:"form-control" }}
            </div>

            <button class="btn btn-secondary" >Salvar Paciente</button>
        </form>
    </div>
</div>
{% endblock content %}

core/templates/core/base.html
{% load static %}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Rita Sforça Estetica Avançada</title>
    <link type="icon" rel="shortcut icon" href="{% static 'core/img/estetica.jpeg' %}"/>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="{% static 'core/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FONT AWESOME ICONS  -->
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <!-- CUSTOM STYLE  -->
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet" />
    <!-- FULL CALENDAR CSS -->
    <!--Icons -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href='{% static "core/css/fullcalendar.min.css" %}' rel='stylesheet' />
    <link href='{% static "core/css/fullcalendar.print.min.css" %}' rel='stylesheet' media='print' />


     <!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0 tituloCabecalho" href="{% url 'core:index' %}">Estetica Avançada</a>
      <!--<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'core:logout_page' %}">Sair</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'core:index' %}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
                 <li class="nav-item">
                <a class="nav-link" href="{% url 'core:novoAgendamento' %}">
                  <span data-feather="shopping-cart"></span>
                  Agendar Consulta
                </a>
              </li>
                  <li class="nav-item">
                <a class="nav-link" href="{% url 'core:adicionaPaciente' %}">
                  <span data-feather="file"></span>
                  Cadastrar Paciente
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:pacientes' %}">
                  <span data-feather="file"></span>
                  Pacientes
                </a>
              </li>



            </ul>


        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-3">
          {% block content %}{% endblock content %}
        </main>
      </div>
    </div>
    {% block modal %}
    {% endblock modal %}
    <!-- CONTENT-WRAPPER SECTION END-->
    <!-- JAVASCRIPT AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
   
    

    <!-- FULL CALENDAR -->
    <script src='{% static "core/js/moment.min.js" %}'></script>
    <script src='{% static "core/js/fullcalendar.min.js" %}'></script>
    <script src='{% static "core/js/pt-br.js" %}'></script>
    <script src='{% static "core/js/jquery.mask.js" %}'></script>
    <script src="{% static 'core/js/sitemask.js' %}"></script>
   {% block scripts %}{% endblock scripts %}
</body>
</html>

core/templates/core/cadastraConsulta.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="page-header text-center mb-3">
        <h1 class="text-secondary">Agendar Consulta</h1>
    </div>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="{% url 'core:novoAgendamento' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="font-weight-bold" for="{{ form.paciente.id_for_label }}">Paciente</label>
                {{ form.paciente | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.servico.id_for_label }}">Serviço</label>
                {{ form.servico | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.data_consulta.id_for_label }}">Data</label>
                {{ form.data_consulta | add_class:"form-control data" }}
                <label class="font-weight-bold" for="{{ form.hora_inicio.id_for_label }}">Hora Inicial</label>
                {{ form.hora_inicio | add_class:"form-control hora" }}
                <label class="font-weight-bold" for="{{ form.hora_final.id_for_label }}">Hora Final</label>
                {{ form.hora_final | add_class:"form-control hora" }}
                <label class="font-weight-bold" for="{{ form.observacoes.id_for_label }}">Observações</label>
                {{ form.observacoes | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.status.id_for_label }}">Status</label>
                {{ form.status | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.form_pagamento.id_for_label }}">Forma de Pagamento</label>
                {{ form.form_pagamento | add_class:"form-control" }}
            </div>
            <button class="btn btn-secondary">Salvar</button>
        </form>
    </div>
</div>
{% endblock content %}
{% block scripts %}

{% endblock scripts %}

core/templates/core/editaConsulta.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="page-header text-center mb-3">
        <h1 class="text-secondary">Editar Consulta</h1>
</div>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form action="{% url 'core:editarAgendamento' agenda.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="font-weight-bold" for="{{ form.paciente.id_for_label }}">Paciente</label>
                {{ form.paciente | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.servico.id_for_label }}">Serviço</label>
                {{ form.servico | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.data_consulta.id_for_label }}">Data</label>
                {{ form.data_consulta | add_class:"form-control data" }}
                <label class="font-weight-bold" for="{{ form.hora_inicio.id_for_label }}">Hora Inicial</label>
                {{ form.hora_inicio | add_class:"form-control hora" }}
                <label class="font-weight-bold" for="{{ form.hora_final.id_for_label }}">Hora Final</label>
                {{ form.hora_final | add_class:"form-control hora" }}
                <label class="font-weight-bold" for="{{ form.observacoes.id_for_label }}">Observações</label>
                {{ form.observacoes | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.status.id_for_label }}">Status</label>
                {{ form.status | add_class:"form-control" }}
                <label class="font-weight-bold" for="{{ form.form_pagamento.id_for_label }}">Forma de Pagamento</label>
                {{ form.form_pagamento | add_class:"form-control" }}
            </div>
            <button class="btn btn-secondary">Salvar</button>
        </form>
    </div>
</div>
{% endblock content %}

core/templates/core/editaPaciente.html
{% extends "core/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="page-header text-center mb-3">
    <h2 class="text-secondary">Editar</h2>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
<form action="{% url 'core:editaPaciente' paciente.id %}" method="post">

    {% csrf_token %}
    <div class="form-group">
         <label for="{{ form.nome.id_for_label }}">Nome</label>
                 {{ form.nome | add_class:"form-control"}}

                <label>Nascimento</label>
                {{ form.nascimento | add_class:"form-control data"}}


                <label for="{{ form.cpf.id_for_label }}">RG</label>
                {{ form.cpf | add_class:"form-control" }}

                 <label for="{{ form.cpf.id_for_label }}">Profissão</label>
                {{ form.profissao | add_class:"form-control" }}


                <label for="{{ form.celular.id_for_label }}">Celular</label>
                {{ form.celular | add_class:"form-control celular" }}


                <label for="{{ form.email.id_for_label }}">Email</label>
                {{ form.email | add_class:"form-control" }}


                <label for="{{ form.cep.id_for_label }}">CEP</label>
                {{ form.cep | add_class:"form-control cep" }}


                <label for="{{ form.endereco.id_for_label }}">Endereço</label>
                {{ form.endereco | add_class:"form-control" }}


                <label for="{{ form.cidade.id_for_label }}">Cidade</label>
                {{ form.cidade | add_class:"form-control" }}
   </div>
    <button class="btn btn-secondary" >Editar Paciente</button>
</form>
    </div>
</div>
{% endblock content %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <h4 class="page-head-line">Dashboard</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="calendar"></div>
    </div>
</div>


<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Detalhes da Consulta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>       
      </div>
      <div class="modal-body sm">
       <strong id="servico"></strong>
       <ul style="list-style: none">
           <li>Paciente:</li>
           <ul>
                <li id="paciente"></li>
           </ul>
            <li>Data da Consulta:</li>
           <ul>
                <li ><span id="data"></span> das <span id="hora_inicio"></span> às  <span id="hora_final"></span></li>
           </ul>
            <li>Observações:</li>
           <ul>
                <li id="observacoes"></li>
           </ul>
           <li>Status da Consulta:</li>
            <ul>
                <li id="status"></li>
            </ul>
           <li>Forma de Pagamento:</li>
            <ul>
                <li id="pagamento"></li>
            </ul>

       </ul>
      </div>

      <div class="modal-footer">
        <button class="btn btn-secondary" id="idAgenda" value="" onclick="editaAgenda(this)">Editar Agendamento</button>
        
      </div>
    </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block scripts %}
<script>

    function editaAgenda(event)
    {
        location.href = "{% url 'core:editarAgendamento' 1234 %}".replace(/1234/, +$(event).val());
    }


  window.onload = function() {

    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listWeek'
      },

      eventClick: function(event)
      {

            let data = moment(event.start).format("DD-MM-YYYY");
            let hora_inicio = moment(event.start).format("HH:mm");
            let hora_final = moment(event.end).format("HH:mm");
            $("#servico").text(event.servico);
            $("#paciente").text(event.paciente);
            $("#data").text(data);
            $("#hora_inicio").text(hora_inicio);
            $("#hora_final").text(hora_final);
            $("#observacoes").text(event.observacoes);
            $("#status").text(event.status);
            $("#idAgenda").val(event.id);
             if(event.pagamento == 'None')
            {
                $("#pagamento").text('Sem informação de Pagamento')
            }
            else
            {
                $('#pagamento').text(event.pagamento)
            }

            $(".modal").modal();
      },
          
      defaultDate: new Date(),
      navLinks: true, // can click day/week names to navigate views
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      themeSystem: 'bootstrap4',

      height: 'parent',
      contentHeight: 600,

      events: [
        {% for var in agenda %}
        {
          title: '{{var}} - {{var.paciente}}',
          start: "{{var.data_consulta | date:'Y-m-d'}} {{var.hora_inicio | date:'H:i'}}",
          end: "{{var.data_consulta | date:'Y-m-d'}} {{var.hora_final | date:'H:i'}}",
          id: {{var.id}},
          {% if var.status.id == 2 %}
            color: 'green',
          {% endif %}
          paciente: '{{var.paciente}}',
          observacoes: "{{var.observacoes}}",
          status: '{{var.status}}',
          pagamento: '{{var.form_pagamento}}',
          servico : '{{var}}'
        },
        {% endfor %}

        

      ],
     
    });

  };
</script>
{% endblock scripts %}

core/templates/core/login.html
{% load static %}
{% load widget_tweaks %}
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Estetica Avançada - Página de Login</title>

    <!-- Bootstrap core CSS -->
     <link href="{% static 'core/css/bootstrap.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="{% static 'core/css/singin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'core:login' %}">

      <img class="mb-4" src="{% static 'core/img/estetica.jpeg' %}" alt="" width="150" height="150">
      <h1 class="h3 mb-3 font-weight-normal">Realizar Login</h1>
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger">
                <li>Usuário ou senha incorretos.</li>
            </div>
        {% endif %}
      <label class="sr-only">Usuário</label>
        {{ form.username | append_attr:"class:form-control" | append_attr:"placeholder:Usuário"}}
      <label class="sr-only">Senha</label>
        {{ form.password | add_class:"form-control" | append_attr:"placeholder:Senha"}}
      <!--<div class="checkbox mb-3">-->
        <!--<label>-->
          <!--<input type="checkbox" value="remembls
          er-me"> Remember me-->
        <!--</label>-->
      <!--</div>-->
        <input type="hidden" name="next" value="{% url 'core:index' %}">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2018</p>
    </form>
  </body>
</html>

core/templates/core/pacientes.html
{% extends 'core/base.html' %}

{% block content %}
<div class="page-header">
    <h2 class="text-secondary">Pacientes</h2>
</div>
<div class="row mb-2 mt-3">
    <div class="col-md-2">
      <a class="btn btn-secondary btn-sm" href="{% url 'core:adicionaPaciente' %}" title="Adicionar novo" >
          <i class="fas fa-user-plus"></i>
      </a>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <tr>
            <th>Nome</th>
            <th>Nascimento</th>
            <th>RG</th>
            <th>Telefone</th>
        </tr>
        {% for paciente in pacientes %}
            <tr>
                <td>
                    {{paciente.nome}}
                </td>
                <td>
                    {{paciente.nascimento | date:"d/m/Y"}}
                </td>
                <td>
                    {% if paciente.cpf is not none %}
                        {{paciente.cpf}}
                    {% endif %}

                </td>
                <td>
                    {{paciente.celular}}
                </td>
                <td>
                    <a class="btn btn-secondary btn-sm" href="{% url 'core:editaPaciente' paciente.id  %}"  title="Editar">
                       <i class="fas fa-user-edit"></i>
                    </a>
                    <a class="btn btn-secondary btn-sm" href="{% url 'core:historicoPaciente' paciente.id %}"  title="Historico do Paciente">
                       <i class="fas fa-history"></i>
                   </a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}
{% block scripts %}
<script>
   window.onload = function(){
    $('[data-toggle="tooltip"]').tooltip();
};
</script>
{% endblock scripts %}